spring:
  application:
    name: ledger-service

server:
  port: 8088
  servlet:
    context-path: /api/ledger-service/v1

management:
  endpoints:
    web:
      exposure:
        include: health

aws:
  dynamodb:
    table-name: LEDGER

  sns:
    ledger-topic-arn: arn:aws:sns:us-east-1:200849340204:ledger-events

  sqs:
    ledger-queue: ledger-queue

wallet:
  initial-balance: 1000
